 List<String> foodItems = [
    'Bag of Rice',
    'Plate of Pepper',
    'Bag of Beans',
    'Tuber Of Yam',
    'Noddles',
    '500g Spaghetti',
    'Crate Of Eggs',
    'Garri',
    'Noodles',
    'Kilo of Fish',
    'Bunch of Plantain',		
'Bunch of Banana',	
'Piece of Apple Fruit',		
'Piece of Orange Fruit',	
'Piece of Watermelon Fruit',		
'Piece of Pineapple Fruit',		
'Usual Plastic Congo of Wheat',		
'Usual Plastic Congo of Elubo',				
'Usual Plastic Congo of Grains',		
'Usual Plastic Congo of Melon',		
'Kilo of Meat',		
'Bunch of Vegetables',
  ];

   /* List<String> foodItems = [
    'Bag of Rice',
    'Plate of Pepper',
    'Bag of Beans',
    'Tuber Of Yam',
    'Noddles',
    '500g Spaghetti',
    'Crate Of Eggs',
    'Garri',
    'Noodles',
    'Kilo of Fish'
  ];*/
  final Map<String, List<String>?> foodSubTypes = {
    'Bag of Rice': ['Foreign', 'Imported'],
    'Bag of Beans': ['Olutu', 'Plebe', 'White', 'oloyin'],
    'Plate of Pepper': [
      'Rodo',
      'Tatase',
      'Sombo/Bawa',
      'Bell/Sweet',
      'Alligator',
      'Black',
      'White',
      'Habanero'
    ],
    'Tuber Of Yam': ['Water Yam', 'Dry Yam', 'White Guinea Yam'],
    '500g Spaghetti': ['Power Pasta', 'Crown Premium', 'Honywell'],
    'Garri': ['Brown', 'White'],
    'Noodles': [],
    'Kilo of Fish': [
      'Alaran/Sardines',
          'Panla',
          'Express',
          'Shawa/Mackerel',
          'Croaker',
          'Catfish',
          'Bonga',
    ],
    'Basket Of Cassava': null,
  };